# Generated by Django 4.0 on 2023-06-12 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoserviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('balance', models.IntegerField(default=0, verbose_name='balance')),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
            options={
                'db_table': 'autoservice',
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=20)),
                ('brand', models.CharField(choices=[('BMW', 'BMW'), ('AUDI', 'Audi'), ('BUGATTI', 'Bugatti'), ('CADILLAC', 'Cadillac'), ('CHEVROLET', 'Chevrolet'), ('CITROEN', 'Citroen'), ('FERRARI', 'Ferrari'), ('FORD', 'Ford'), ('LEXUS', 'Lexus')], max_length=20)),
                ('fuel_type', models.CharField(choices=[('PETROL', 'petrol'), ('DISEL', 'disel'), ('CNG', 'CNG'), ('BIO_DISEL', 'bio disel'), ('ELECTRIC', 'electric')], max_length=20)),
            ],
            options={
                'db_table': 'car',
            },
        ),
        migrations.CreateModel(
            name='PreferredCarParametersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('brand', models.CharField(choices=[('BMW', 'BMW'), ('AUDI', 'Audi'), ('BUGATTI', 'Bugatti'), ('CADILLAC', 'Cadillac'), ('CHEVROLET', 'Chevrolet'), ('CITROEN', 'Citroen'), ('FERRARI', 'Ferrari'), ('FORD', 'Ford'), ('LEXUS', 'Lexus')], max_length=20)),
                ('fuel_type', models.CharField(choices=[('PETROL', 'petrol'), ('DISEL', 'disel'), ('CNG', 'CNG'), ('BIO_DISEL', 'bio disel'), ('ELECTRIC', 'electric')], max_length=20)),
                ('autoservice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferred_car_parameters', to='Autoservice.autoservicemodel')),
            ],
            options={
                'db_table': 'preferred_car_parameters',
            },
        ),
        migrations.CreateModel(
            name='AutoserviceRegularCustomers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('number_of_purchases', models.IntegerField(default=0)),
                ('autoservice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Autoservice.autoservicemodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.usermodel')),
            ],
            options={
                'db_table': 'autoservice_regular_customers',
            },
        ),
        migrations.AddField(
            model_name='autoservicemodel',
            name='regular_customers',
            field=models.ManyToManyField(related_query_name='autoservices', through='Autoservice.AutoserviceRegularCustomers', to=settings.AUTH_USER_MODEL),
        ),
    ]
